name: result

on: [push]

jobs:
  build_and_run_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: mkdir artifacts
      run : mkdir artifacts

    - name: load dependecy
      run : pip3 install -r ${{ github.workspace }}/requirements.txt
    
    - name: show dependency
      run: |
          echo "gcc path: $(which gcc)"
          echo "gcc version: $(gcc --version)"
          echo "python3 path: $(which python3)"
          echo "python3 version: $(python3 --version)"

    - name: create obj directory
      run: mkdir ${{ github.workspace }}/obj 

    - name: build Router
      run:  make -j8

    - name: run Router
      run:  |
        for i in {0..99}; do
          echo "Running case test$i.txt"
          ${{ github.workspace }}/router ${{ github.workspace }}/case/test$i.txt ${{ github.workspace }}/artifacts/test$i.txt
        done

    - name: verify output
      run:  python3 ${{ github.workspace }}/visual.py --dir ./artifacts/

    
    - name: save routing result
      uses: actions/upload-artifact@v3
      with:
        name: routing_result
        path: ${{ github.workspace }}/artifacts/*

    - name: rm -rf artifacts
      run : rm -rf artifacts
    
  
