name: verifier

on: [push]

jobs:
  verifier:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: mkdir artifacts
      run : mkdir artifacts

    - name: show dependency
      run: |
          echo "gcc path: $(which gcc)"
          echo "gcc version: $(gcc --version)"

    - name: create obj directory
      run: mkdir ${{ github.workspace }}/obj 

    - name: build Router
      run:  make -j8

    - name: run Router
      run:  |
        for i in {0..99}; do
          echo "Running case test$i.txt"
          ${{ github.workspace }}/router ${{ github.workspace }}/case/test$i.txt ${{ github.workspace }}/artifacts/test$i.txt
        done

    - name: verify output
      run:  |
        for i in {0..99}; do
          echo "Running case test$i.txt."
          ./verifier ./artifacts/test$i.txt > ./artifacts/log$i.txt
        done
        not_pass_file=""
        for i in {0..99}; do
          if grep -q "Error" ./artifacts/log$i.txt; then
            echo "Error found in case test$i.txt."
            echo "Please run the following code to check the log."
            echo "./verifier ./out/test$i.txt"
            not_pass_file="$not_pass_file$i/"
          else
              echo "Passed."
          fi
        done
        if [ -n $not_pass_file ]; then
          echo "Failed at test{$not_pass_file}.txt"
          exit 1
        fi

    - name: rm -rf artifacts
      run : rm -rf artifacts
    
  
